services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Vim\Settings\Middleware\ConfigsMiddlewareInterface:
            tags: ['settings.middleware.configs']

    Vim\Settings\:
        resource: '../../*'
        exclude: '../../{DependencyInjection}'

    Vim\Settings\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Vim\Settings\Service\SettingsCollection:
        factory: ['@Vim\Settings\Factory\SettingsCollectionFactory', 'create']

    Vim\Settings\Middleware\ConfigsMiddlewareProcessor:
        arguments:
            - !tagged_iterator settings.middleware.configs
